# Site settings
title: Twitter Swiss Army Knife
markdown: redcarpet
baseurl: /planets-of-the-universe
exclude: ['README.md']
# Build settings
markdown: rdiscount
markdown_ext:  markdown,mkdown,mkdn,mkd,md