# Site settings
title: Planets of the universe
baseurl: /planets-of-the-universe
exclude: ['README.md']
# Build settings
markdown: rdiscount
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: pretty